const VERSION='v21';
const CORE_CACHE=`fitstart-core-${VERSION}`;
// Animațiile selectate pentru offline rămân disponibile după actualizări.
const MEDIA_CACHE='fitstart-media-v1';
const CORE=['./','./index.html','./styles.css?v=21','./data.js?v=21','./motion.js?v=21','./app.js?v=21','./manifest.webmanifest','./assets/anatomy-sprites.png','./assets/icon-192.png','./assets/icon-512.png','./assets/icon-180.png'];
const GROUPS={
  'Piept':['impins-inclinat-gantere.webp','impins-inclinat-aparat.webp','fluturari-jos-sus.webp','impins-piept-gantere.webp','presa-piept-aparat.webp','flotari-clasice.webp','flotari-ridicate.webp','impins-declinat-aparat.webp','fluturari-sus-jos.webp'],
  'Spate':['tractiuni-asistate.webp','helcometru-neutru.webp','pullover-cablu.webp','ramat-aparat.webp','ramat-cablu.webp','fluturari-inverse.webp','extensii-lombare-corect.webp','bird-dog.webp','indreptari-romanesti.webp'],
  'Umeri':['presa-umeri-aparat.webp','ridicari-frontale-disc.webp','landmine-unilateral.webp','ridicari-laterale-gantere.webp','ridicari-laterale-cablu.webp','ridicari-laterale-aparat.webp','fluturari-inverse.webp','face-pull.webp','ridicari-posterioare-banca.webp'],
  'Picioare':['genuflexiune-cutie.webp','presa-picioare.webp','extensii-picioare.webp','flexii-femurali-aparat.webp','indreptari-romanesti-gantere.webp','flexii-femurali-mingea.webp','hip-thrust-aparat.webp','podul-fesier.webp','abductii-aparat.webp','ridicari-varfuri-picioare.webp','ridicari-varfuri-sezut.webp','presa-gambe.webp'],
  'Biceps':['flexii-inclinate-gantere.webp','flexii-ciocan.webp','flexii-cablu-spate.webp','flexii-preacher-aparat.webp','flexii-concentrate.webp','flexii-ez-larga.webp'],
  'Triceps':['extensii-cap-cablu.webp','extensii-gantera-sezut.webp','skull-crusher-ez.webp','impingeri-cablu-bara.webp','impingeri-cablu-inversa.webp','flotari-inguste-banca.webp','impingeri-franghia-iulian-v1.mp4','presa-aparat-ingusta.webp','extensii-unilaterale-cablu.webp'],
  'Abdomen':['crunch-aparat.webp','crunch-saltea.webp','crunch-cablu-genunchi.webp','ridicari-genunchi-scaun.webp','reverse-crunch.webp','dead-bug.webp','pallof-press.webp','plansa-laterala-genunchi.webp','wood-chop.webp'],
  'Antebrațe':['flexii-incheieturii.webp','strangere-gripper.webp','mentinere-gantere.webp','extensii-incheieturii.webp','flexii-inverse-ez.webp','pronatie-supinatie.webp']
};
const mediaUrl=name=>new URL(`./assets/${name}`,self.registration.scope).href;
self.addEventListener('install',event=>event.waitUntil(caches.open(CORE_CACHE).then(cache=>cache.addAll(CORE))));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>{const oldCore=key.startsWith('fitstart-core-')&&key!==CORE_CACHE;const oldMedia=key.startsWith('fitstart-media-')&&key!==MEDIA_CACHE;const legacy=/^fitstart-v\d+/.test(key);return oldCore||oldMedia||legacy}).map(key=>caches.delete(key)));await self.clients.claim()})()));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const request=event.request,url=new URL(request.url);if(url.origin!==self.location.origin)return;const isMedia=url.pathname.includes('/assets/')&&/\.(webp|png|mp4)$/i.test(url.pathname);if(request.mode==='navigate'){event.respondWith(fetch(request).then(response=>{if(response.ok){const copy=response.clone();event.waitUntil(caches.open(CORE_CACHE).then(cache=>cache.put('./index.html',copy)))}return response}).catch(async()=>await caches.match('./index.html')||Response.error()));return}event.respondWith(caches.match(request).then(hit=>hit||fetch(request).then(response=>{if(response.ok&&response.type==='basic')event.waitUntil(caches.open(isMedia?MEDIA_CACHE:CORE_CACHE).then(cache=>cache.put(request,response.clone())));return response}).catch(()=>isMedia?new Response('',{status:503,statusText:'Offline media unavailable'}):Response.error())))});
async function reply(clientId,message){const client=await self.clients.get(clientId);client?.postMessage(message)}
self.addEventListener('message',event=>{const data=event.data||{};if(data.type==='SKIP_WAITING'){self.skipWaiting();return}if(data.type==='CACHE_GROUP'){event.waitUntil((async()=>{const files=GROUPS[data.group]||[],cache=await caches.open(MEDIA_CACHE);let done=0,failed=0;for(const file of files){const url=mediaUrl(file);if(!(await cache.match(url))){try{const response=await fetch(url);if(response.ok)await cache.put(url,response);else failed++}catch{failed++}}done++;await reply(event.source.id,{type:'CACHE_PROGRESS',group:data.group,done,total:files.length,failed})}await reply(event.source.id,{type:failed?'CACHE_FAILED':'CACHE_DONE',group:data.group,failed,total:files.length})})());return}if(data.type==='CACHE_STATUS'){event.waitUntil((async()=>{const cache=await caches.open(MEDIA_CACHE),status={};for(const [group,files] of Object.entries(GROUPS)){let count=0;for(const file of files)if(await cache.match(mediaUrl(file)))count++;status[group]={count,total:files.length}}await reply(event.source.id,{type:'CACHE_STATUS',status})})());return}if(data.type==='CLEAR_MEDIA'){event.waitUntil(caches.delete(MEDIA_CACHE).then(()=>reply(event.source.id,{type:'MEDIA_CLEARED'})))}});
